config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root 'people#index'

  resources :people, constraints: {id: /[A-Za-z0-9\._-]+/}, only: [:show, :photo] do
    get :photo
  end
  resource :sessions, only: [:new, :create, :destroy] do
  end
  resource :profile, only: [:edit, :update_passowrd] do
    patch :update_passowrd
    patch :update_photo
  end

  namespace :api do
    namespace :public do
      namespace :v1 do
        resources :people_photo, only: [:show], constraints: {id: /[A-Za-z0-9\._-]+/}
      end
    end
  end

  namespace :admin do
    constraints CanAccessResque do
      mount Resque::Server, at: 'resque'
    end

    get '', to: redirect('/admin/people'), as: :index
    resources :people, constraints: {id: /[A-Za-z0-9\._-]+/} do
      resource :people_photo, constraints: {person_id: /[A-Za-z0-9\._-]+/}, only: [:update] do
      end
    end

    resources :groups, constraints: {id: /[A-Za-z0-9\._-]+/} do
      resource :groups_members, constraints: {group_id: /[A-Za-z0-9\._-]+/}, only: [:create, :destroy] do
      end
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < BaseController
  before_filter :set_person
  before_filter :set_person_photo

  def edit
  end

  def update_passowrd
    respond_to do |format|
      if @person.update(update_passowrd_params)
        format.html { redirect_to edit_profile_path, flash: {success: t('ldap.person_password.flash.updated')} }
      else
        flash.now[:alert] = Ldap::Person.last_error_message unless Ldap::Person.last_error_message.empty?
        format.html { render action: 'edit' }
      end
    end
  end

  def update_photo
    @person_photo.dn = @person.dn
    @person_photo.update(update_photo_params)
    respond_to do |format|
      if @person_photo.update(update_photo_params)
        format.html { redirect_to edit_profile_path, flash: {success: t('ldap.person_photo.flash.updated')} }
      else
        flash.now[:alert] = Ldap::PersonPhoto.last_error_message unless Ldap::PersonPhoto.last_error_message.empty?
        format.html { render action: 'edit' }
      end
    end
  end

  protected

  def update_passowrd_params
    params.require(:ldap_person).permit(:password, :password_confirmation)
  end

  def update_photo_params
    params.fetch(:ldap_person_photo, {}).permit(:upload_image)
  end

  def set_person
    @person = current_user
  end

  def set_person_photo
    @person_photo = Ldap::PersonPhoto.new
  end
end

app/views/profiles/edit.haml
- flash.each do |name, msg|
  .row
    .large-12.columns
      %div{class: flash_class(name) }
        = msg

.row
  .large-5.columns
    = form_for @person, url:update_passowrd_profile_path, method: :patch do |f|
      .row.collapse.prefix-radius
        .small-5.columns
          %span.prefix
            Password
        .small-7.columns
          = f.password_field :password
        = field_error_message(@person, :password)
      .row.collapse.prefix-radius
        .small-5.columns
          %span.prefix
            Password confirm
        .small-7.columns
          = f.password_field :password_confirmation
        = field_error_message(@person, :password_confirmation)

      = f.button "Update Password"

  .large-7.columns
    .row
      .small-4.columns
        = link_to "#", class: "th" do
          = image_tag  person_photo_path(@person.uid, size: 'medium')
      .small-8.columns
        = form_for @person_photo, url: update_photo_profile_path, method: :patch do |f|
          = f.file_field :upload_image
          = f.hidden_field :uid, value: @person.uid
          = field_error_message(@person_photo, :upload_image)
          = f.button "Update Photo", class:""