config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root 'people#index'

  resources :people, constraints: {id: /[A-Za-z0-9\._-]+/}, only: [:show, :photo] do
    get :photo
  end
  resource :sessions, only: [:new, :create, :destroy] do
  end
  resource :profile, only: [:edit, :update_passowrd] do
    patch :update_passowrd
    patch :update_photo
  end

  namespace :api do
    namespace :public do
      namespace :v1 do
        resources :people_photo, only: [:show], constraints: {id: /[A-Za-z0-9\._-]+/}
      end
    end
  end

  namespace :admin do
    constraints CanAccessResque do
      mount Resque::Server, at: 'resque'
    end

    get '', to: redirect('/admin/people'), as: :index
    resources :people, constraints: {id: /[A-Za-z0-9\._-]+/} do
      resource :people_photo, constraints: {person_id: /[A-Za-z0-9\._-]+/}, only: [:update] do
      end
    end

    resources :groups, constraints: {id: /[A-Za-z0-9\._-]+/} do
      resource :groups_members, constraints: {group_id: /[A-Za-z0-9\._-]+/}, only: [:create, :destroy] do
      end
    end
  end

end

app/models/ldap/person.rb
#TODO: нужен автоинкримент uidnumber
class Ldap::Person < Ldap::Entity

  attr_accessor :dn, :objectclass, :uid, :cn, :sn, :givenname, :l, :o, :mail, :skype, :title,
                :employeetype, :mobile, :uidnumber, :gidnumber, :homedirectory, :password

  DN_ATTR = :uid
  CLASSES = ["person", "inetOrgPerson", "organizationalPerson", "posixAccount", "top", "vuaro"]
  ARRAY_ATTR = [:mail, :objectclass, :mobile]
  EMPLOY_TYPES = %w(staff fired external parnter system)

  validates :dn, length: {in: 1..1000}, presence: true
  validates :givenname, :sn, :l, :o, :skype, :title, length: {in: 1..100}, presence: true
  validates :uid, length: {in: 1..100}, presence: true, format: { with: /\A[a-zA-Z\.\_\-]+\z/ }
  validates :objectclass, :mail, :mobile, presence: true
  validates :employeetype, presence: true, inclusion: EMPLOY_TYPES
  validates :password, length: { minimum: 8 }, confirmation: true, allow_blank: true
  validates :uidnumber, :gidnumber, presence: true, numericality: { only_integer: true, greater_than: 1, less_than: 65000 }

  class << self

    def search(filter, attrs)
      init_ldap_connection
      @@ldap.search(base: Ldap::Base::PEOPLE_BASE,
                    filter: filter,
                    attributes: attrs,
                    scope: Net::LDAP::SearchScope_SingleLevel,
                    sort_controls: [DN_ATTR],
                    return_result: true)
    end

    def find_by_filter(filter)
      #filter = Net::LDAP::Filter.eq(DN_ATTR, uid)
      result = self.search(filter, Ldap::Person.attributes)
      Ldap::Person.mapping_array(result)
    end

    def all
      filter = Net::LDAP::Filter.eq(DN_ATTR, "*")
      find_by_filter(filter)
    end

    def find(uid)
      filter = Net::LDAP::Filter.eq(DN_ATTR, uid)
      result = find_by_filter(filter)
      result.first
    end

    def find_by_employeetype(employeetype)
      filter_dn = Net::LDAP::Filter.eq(DN_ATTR, "*")
      filter_employeetype = Net::LDAP::Filter.eq(:employeetype, employeetype)
      find_by_filter(Net::LDAP::Filter.join(filter_employeetype, filter_dn))
    end

    def authenticate(uid, password)
      if self.valid_attribute?(:uid, uid)
        return self.find(uid) if Ldap::Base.authenticate(DN_ATTR.to_s, uid, password)
      end
      nil
    end

    def valid_attribute?(attr, value)
      mock = self.new(attr => value)
      if mock.valid?
        true
      else
        !mock.errors.has_key?(attr)
      end
    end
  end

  def initialize(attributes = {})
    self.mail = [""]
    self.mobile = [""]
    super
  end

  def dn
    "uid=#{uid},#{PEOPLE_BASE}"
  end

  def cn
    "#{givenname} #{sn}"
  end

  def homedirectory
    "/home/#{uid}"
  end

  def groups
    Ldap::Group.get_person_groups(self.dn)
  end

  def self.employeetype_keywords
    EMPLOY_TYPES + ['all']
  end


  #methods ldap
  def save
    self.password = nil
    ops = []
    self.cn = "#{givenname} #{sn}"
    attributes.each do |name|
      ops << [:replace, name, send(name)] unless name == :dn or send(name).blank?
    end

    #создание недостающих классов
    need_add_classes = CLASSES - self.objectclass
    need_add_classes.each do |name_class|
      ops << [:add, :objectclass, name_class]
    end

    @@ldap.modify(dn: self.dn, operations: ops)
  end

  def create
    result = true
    clear_password = self.password
    if self.valid?
      self.password = nil
      attrs = {}
      attributes.each do |name|
        attrs[name] = send(name) unless name == :dn or send(name).blank?
      end

      result = @@ldap.add(dn: self.dn, attributes: attrs)
    end

    result and update_password(clear_password)
  end

  def update(params)
    if params[:password].blank?
      params.delete(:password_confirmation)
      params.delete(:password)
    end

    params.each do |name, value|
      send("#{name}=", value)
    end

    if self.valid?
      clear_password = self.password
      result_save = save
      result_update_password = update_password(clear_password)

      if result_save and result_update_password
        external_services(clear_password)
      end
      result_save and result_update_password
    end
  end

  protected

  def update_password(clear_password)
    if clear_password and !clear_password.blank?
      result =  @@ldap.replace_attribute self.dn, :userPassword, generate_hash_password(clear_password)
      return result
    end
    true
  end

  def external_services(clear_password)
    Resque.enqueue(GmailExternalServiceJob, self.uid, clear_password) if Settings.external_services.enable.include?('gmail_admin')
    Resque.enqueue(YandexExternalServiceJob, self.uid, clear_password) if Settings.external_services.enable.include?('yandex_mail_admin')
    Resque.enqueue(RedmineExternalServiceJob, self.uid, clear_password) if Settings.external_services.enable.include?('redmine')
  end

  #Only SSHA
  def generate_hash_password(secret)
    salt = SecureRandom.hex(8)
    "{SSHA}"+Base64.encode64(Digest::SHA1.digest(secret + salt) + salt).chomp!
  end

end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < Admin::BaseController

  def index
    employeetype = params[:employeetype]
    employeetype ||= "staff"
    employeetype = "*" if employeetype == "all"

    @peoples = Ldap::Person.find_by_employeetype(employeetype)
  end

  def show

  end

  def new
    @person = Ldap::Person.new
  end

  def create
    @person = Ldap::Person.new(person_params)
    respond_to do |format|
      if @person.create
        format.html { redirect_to edit_admin_person_path(@person.uid), flash: {success: t('ldap.person.flash.created')} }
      else
        flash.now[:alert] = Ldap::Person.last_error_message unless Ldap::Person.last_error_message.empty?
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    @person_photo = Ldap::PersonPhoto.new
    @person = Ldap::Person.find(params[:id])
  end


  #TODO: нужно доделать редактирование мульти записей (mail, phone)
  def update
    @person_photo = Ldap::PersonPhoto.new
    @person = Ldap::Person.find(params[:id])
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to edit_admin_person_path(@person.uid), flash: {success: t('ldap.person.flash.updated')} }
      else
        flash.now[:alert] = Ldap::Person.last_error_message unless Ldap::Person.last_error_message.empty?
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy

  end


  protected

  def person_params
    params.require(:ldap_person).permit(:uid, :cn, :sn, :givenname, :l, :o, :skype, :title,
                                        :employeetype, :uidnumber, :gidnumber, :mobile, :password, :password_confirmation, :mobile => [], :mail => [])
  end

end

app/controllers/people_controller.rb
class PeopleController < BaseController

  def index
    employeetype_list = %w(external staff partner)
    filters = employeetype_list.map { |name| Net::LDAP::Filter.eq(:employeetype, name) }
    search_filter = Net::LDAP::Filter.construct("(|#{ filters.join("") })")
    @peoples = Ldap::Person.find_by_filter(search_filter)
  end

  def show
    @person = Ldap::Person.find(params[:id])
  end

  def photo
    params[:size] ||= 'small'
    person = Ldap::Person.find(params[:person_id]) || Ldap::Person.new
    photo = Ldap::PersonPhoto.new({dn: person.dn, uid: person.uid})
    send_file photo.get(params[:size]), type: 'image/jpeg', disposition: 'inline'
  end

end

app/helpers/admin/people_helper.rb
module Admin::PeopleHelper
  def is_active_employeetype(params, value)
    if params[:employeetype].blank? and value == 'staff'
      "active"
    elsif params[:employeetype] == value
      "active"
    end
  end
end

app/views/admin/people/_breadcrumbs.haml
%ul.breadcrumbs
  %li
    = link_to 'People', admin_people_path
  %li
    = link_to 'Edit', edit_admin_person_path(@person.uid)
  %li.current
    = link_to @person.uid, edit_admin_person_path(@person.uid)

app/views/admin/people/_form.haml
- flash.each do |name, msg|
  .row
    .large-12.columns
      %div{class: flash_class(name) }
        = msg

.row{style: 'padding-bottom:40px;'}
  .large-5.columns
    .row
      .small-6.columns
        = link_to "#", class: "th" do
          = image_tag  person_photo_path(@person.uid, size: 'medium')
      .small-6.columns
        = form_for @person_photo, url:admin_person_people_photo_path(@person.uid), method: :patch do |f|
          = f.file_field :upload_image
          = f.button "Update Photo", class:""

.row
  .large-12.columns
    = form_for @person, url:admin_person_path(@person.uid), method: :put do |f|
      .large-5.columns
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              DN
          .small-9.columns
            = f.text_field :dn, disabled:true
          = field_error_message(@person, :dn)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              UID
          .small-9.columns
            = f.text_field :uid
          = field_error_message(@person, :uid)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              First Name
          .small-9.columns
            = f.text_field :givenname
          = field_error_message(@person, :givenname)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Last Name
          .small-9.columns
            = f.text_field :sn
          = field_error_message(@person, :sn)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Post
          .small-9.columns
            = f.text_field :title
          = field_error_message(@person, :title)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Organization
          .small-9.columns
            = f.text_field :o
          = field_error_message(@person, :o)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Location
          .small-9.columns
            = f.text_field :l
          = field_error_message(@person, :l)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Type
          .small-9.columns
            = f.select :employeetype, options_for_select(Ldap::Person::EMPLOY_TYPES, @person.employeetype)
          = field_error_message(@person, :employeetype)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Skype
          .small-9.columns
            = f.text_field :skype
          = field_error_message(@person, :skype)
        - @person.mobile.each do |mobile|
          .row.collapse.prefix-radius
            .small-3.columns
              %span.prefix
                = fa_icon 'phone'
            .small-9.columns
              = f.text_field "mobile][", value: mobile, :id=>"item-#{SecureRandom.uuid}"
            = field_error_message(@person, :mobile)
        - @person.mail.each do |mail|
          .row.collapse.prefix-radius
            .small-3.columns
              %span.prefix
                = fa_icon 'envelope'
            .small-9.columns
              = f.text_field "mail][", value: mail, :id=>"item-#{SecureRandom.uuid}"
            = field_error_message(@person, :mail)
        = f.button "Update"
      .large-1.columns
      .large-5.columns
        .row.collapse.prefix-radius
          .small-5.columns
            %span.prefix
              Password
          .small-7.columns
            = f.password_field :password
          = field_error_message(@person, :password)
        .row.collapse.prefix-radius
          .small-5.columns
            %span.prefix
              Password confirm
          .small-7.columns
            = f.password_field :password_confirmation
          = field_error_message(@person, :password_confirmation)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Uid Number
          .small-9.columns
            = f.text_field :uidnumber
          = field_error_message(@person, :uidnumber)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Gid Number
          .small-9.columns
            = f.text_field :gidnumber
          = field_error_message(@person, :gidnumber)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Home Dir
          .small-9.columns
            = f.text_field :homedirectory
          = field_error_message(@person, :homedirectory)
        .row.collpase.prefix-radius
          .small-12.columns
            ObjectClass
            %ul.disc
              - @person.objectclass.each do |objectclass|
                %li
                  = objectclass
      .large-1.columns

.row
  .large-12.columns
    %h2
      Member of groups
    %ul.disc
      - @person.groups.each do |group|
        %li
          = link_to group.cn, edit_admin_group_path(group.cn)

app/views/admin/people/edit.haml
.row
  .large-12.columns
    = render 'breadcrumbs'

= render 'form'

app/views/admin/people/index.haml
-# coding: UTF-8
.row
  .large-9.columns
    .row.collapse
      .small-10.columns
        = text_field_tag "search", "search"
      .small-2.columns
        = link_to params.merge({:q => "search"}), class: "button postfix" do
          = fa_icon 'search'
    .row
      .small-12.columns
        %dl.sub-nav
          %dt
            Filter:
          - Ldap::Person.employeetype_keywords.each do |employeetype|
            %dd{class: "#{is_active_employeetype(params, employeetype)}"}
              = link_to employeetype, params.merge({:employeetype => employeetype})
  .large-3.columns
    = link_to new_admin_person_path, class: "button postfix" do
      = fa_icon 'plus'
      Create
.row
  .large-12.columns
    %table.table-expand
      %thead
        %tr
          %th
            photo
          %th
            UID
          %th
            Name
          %th
            Type
          %th
            Post
          %th
            Organization
          %th
            Location
      %tbody
        - @peoples.each do |person|
          %tr
            %td
              = image_tag person_photo_path(person.uid, size: 'small')
            %td
              = link_to person.uid, edit_admin_person_path(person.uid)
            %td
              = person.cn
            %td
              = person.employeetype
            %td
              = person.title
            %td
              = person.o
            %td
              = person.l

app/views/admin/people/new.haml
- flash.each do |name, msg|
  .row
    .large-12.columns
      %div{class: flash_class(name) }
        = msg

= form_for @person, url:admin_people_path, method: :post do |f|
  .large-5.columns
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          DN
      .small-9.columns
        = f.text_field :dn, disabled:true
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          UID
      .small-9.columns
        = f.text_field :uid
      = field_error_message(@person, :uid)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          First Name
      .small-9.columns
        = f.text_field :givenname
      = field_error_message(@person, :givenname)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Last Name
      .small-9.columns
        = f.text_field :sn
      = field_error_message(@person, :sn)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Post
      .small-9.columns
        = f.text_field :title
      = field_error_message(@person, :title)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Organization
      .small-9.columns
        = f.text_field :o
      = field_error_message(@person, :o)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Location
      .small-9.columns
        = f.text_field :l
      = field_error_message(@person, :l)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Type
      .small-9.columns
        = f.select :employeetype, options_for_select(Ldap::Person::EMPLOY_TYPES, @person.employeetype)
      = field_error_message(@person, :employeetype)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Skype
      .small-9.columns
        = f.text_field :skype
      = field_error_message(@person, :skype)
    - @person.mobile.each do |mobile|
      .row.collapse.prefix-radius
        .small-3.columns
          %span.prefix
            = fa_icon 'phone'
        .small-9.columns
          = f.text_field "mobile][", value: mobile, :id=>"item-#{SecureRandom.uuid}"
        = field_error_message(@person, :mobile)
    - @person.mail.each do |mail|
      .row.collapse.prefix-radius
        .small-3.columns
          %span.prefix
            = fa_icon 'envelope'
        .small-9.columns
          = f.text_field "mail][", value: mail, :id=>"item-#{SecureRandom.uuid}"
        = field_error_message(@person, :mail)
    = f.button "Create"
  .large-1.columns
  .large-5.columns
    .row.collapse.prefix-radius
      .small-5.columns
        %span.prefix
          Password
      .small-7.columns
        = f.password_field :password
      = field_error_message(@person, :password)
    .row.collapse.prefix-radius
      .small-5.columns
        %span.prefix
          Password confirm
      .small-7.columns
        = f.password_field :password_confirmation
      = field_error_message(@person, :password_confirmation)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Uid Number
      .small-9.columns
        = f.text_field :uidnumber
      = field_error_message(@person, :uidnumber)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Gid Number
      .small-9.columns
        = f.text_field :gidnumber
      = field_error_message(@person, :gidnumber)
    .row.collpase.prefix-radius
      .small-12.columns
        ObjectClass
        %ul.disc
          - @person.objectclass.each do |objectclass|
            %li
              = objectclass
  .large-1.columns