config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root 'people#index'

  resources :people, constraints: {id: /[A-Za-z0-9\._-]+/}, only: [:show, :photo] do
    get :photo
  end
  resource :sessions, only: [:new, :create, :destroy] do
  end
  resource :profile, only: [:edit, :update_passowrd] do
    patch :update_passowrd
    patch :update_photo
  end

  namespace :api do
    namespace :public do
      namespace :v1 do
        resources :people_photo, only: [:show], constraints: {id: /[A-Za-z0-9\._-]+/}
      end
    end
  end

  namespace :admin do
    constraints CanAccessResque do
      mount Resque::Server, at: 'resque'
    end

    get '', to: redirect('/admin/people'), as: :index
    resources :people, constraints: {id: /[A-Za-z0-9\._-]+/} do
      resource :people_photo, constraints: {person_id: /[A-Za-z0-9\._-]+/}, only: [:update] do
      end
    end

    resources :groups, constraints: {id: /[A-Za-z0-9\._-]+/} do
      resource :groups_members, constraints: {group_id: /[A-Za-z0-9\._-]+/}, only: [:create, :destroy] do
      end
    end
  end

end

app/models/ldap/group.rb
class Ldap::Group < Ldap::Entity

  attr_accessor :dn, :cn, :objectclass, :uniquemember, :description, :gidnumber


  CLASSES = ["groupOfUniqueNames", "posixGroup", "top"]
  DN_ATTR = :cn
  ARRAY_ATTR = [:objectclass, :uniquemember]

  validates :dn, length: {in: 1..1000}, presence: true
  validates :description, :cn, length: {in: 1..100}, presence: true
  validates :gidnumber, presence: true, numericality: { only_integer: true, greater_than: 1, less_than: 65000 }

  def initialize(attributes = {})
    self.description = ""
    super
  end

  def dn
    "cn=#{cn},#{GROUP_BASE}"
  end

  class << self

    def search(filter, attrs)
      init_ldap_connection
      @@ldap.search(base: Ldap::Base::GROUP_BASE,
                    filter: filter,
                    attributes: attrs,
                    scope: Net::LDAP::SearchScope_SingleLevel,
                    sort_controls: [DN_ATTR],
                    return_result: true)
    end

    def find(cn)
      filter = Net::LDAP::Filter.eq(DN_ATTR, cn)
      result_list = self.search(filter, Ldap::Group.attributes)
      return nil if result_list.empty?
      obj = new
      obj.mapping(result_list.first)
    end

    def get_person_groups(dn)
      filter = Net::LDAP::Filter.eq(:uniquemember, dn)
      result_list = self.search(filter, Ldap::Group.attributes)
      Ldap::Group.mapping_array(result_list)
    end

    def all
      filter = Net::LDAP::Filter.eq(DN_ATTR, "*")
      result_list = self.search(filter, Ldap::Group.attributes)
      Ldap::Group.mapping_array(result_list)
    end
  end

  def is_member?(dn)
    uniquemember.include?(dn)
  end


  def add_member(dn)
    unless is_member?(dn)
      ops = []
      ops << [:add, :uniquemember, dn]
      @@ldap.modify(dn: self.dn, operations: ops)
    end
  end

  def remove_member(dn)
    if is_member?(dn)
      ops = []
      ops << [:delete, :uniquemember, dn]
      @@ldap.modify(dn: self.dn, operations: ops)
    end
  end

  def create
    if self.valid?
      attrs = {}
      attributes.each do |name|
        attrs[name] = send(name) unless name == :dn or send(name).blank?
      end

      @@ldap.add(dn: self.dn, attributes: attrs)
    end
  end

  def save
    ops = []
    attributes.each do |name|
      ops << [:replace, name, send(name)] unless [:dn, :uniquemember].include?(name) or send(name).blank?
    end
    #создание недостающих классов
    need_add_classes = CLASSES - self.objectclass
    need_add_classes.each do |name_class|
      ops << [:add, :objectclass, name_class]
    end

    @@ldap.modify(dn: self.dn, operations: ops)
  end

  def update(params)
    params.each do |name, value|
      send("#{name}=", value)
    end
    if self.valid?
      save
    end
  end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController

  def index
    @groups = Ldap::Group.all
  end

  def new
    @group = Ldap::Group.new
  end

  def create
    @group = Ldap::Group.new(group_params)
    respond_to do |format|
      if @group.create
        format.html { redirect_to edit_admin_group_path(@group.cn), flash: {success: t('ldap.group.flash.created')} }
      else
        flash.now[:alert] = Ldap::Group.last_error_message unless Ldap::Group.last_error_message.empty?
        format.html { render action: 'new' }
      end
    end
  end

  def edit
    @group = Ldap::Group.find(params[:id])
  end

  def update
    @group = Ldap::Group.find(params[:id])
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to edit_admin_group_path(@group.cn), flash: {success: t('ldap.group.flash.updated')} }
      else
        flash.now[:alert] = Ldap::Group.last_error_message unless Ldap::Group.last_error_message.empty?
        format.html { render action: 'edit' }
      end
    end
  end


  def group_params
    params.require(:ldap_group).permit(:cn, :description, :gidnumber)
  end
end

app/views/admin/groups/_breadcrumbs.haml
%ul.breadcrumbs
  %li
    = link_to 'Groups', admin_groups_path
  %li
    = link_to 'Edit', edit_admin_group_path(@group.cn)
  %li.current
    = link_to @group.cn, edit_admin_group_path(@group.cn)

app/views/admin/groups/_form.haml
- flash.each do |name, msg|
  .row
    .large-12.columns
      %div{class: flash_class(name) }
        = msg
.row
  .large-12.columns
    .large-5.columns
      = form_for @group, url: admin_group_path(@group.cn), method: :put do |f|
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              DN
          .small-9.columns
            = f.text_field :dn, disabled:true
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              CN
          .small-9.columns
            = f.text_field :cn, disabled:true
          = field_error_message(@group, :cn)
        .row.collapse.prefix-radius
          .small-3.columns
            %span.prefix
              Gid Number
          .small-9.columns
            = f.text_field :gidnumber
          = field_error_message(@group, :gidnumber)
        .row.collapse.prefix-radius
          %label
            %span.prefix
              Description
            = f.text_area :description
          = field_error_message(@group, :description)
        .row.collpase.prefix-radius
          .small-12.columns
            ObjectClass
            %ul.disc
              - @group.objectclass.each do |objectclass|
                %li
                  = objectclass
        = f.button "Update"
    .large-7.columns
      .row
        = form_for Ldap::GroupMember.new, url: admin_group_groups_members_path(@group.cn), method: :post do |f|
          .small-9.columns
            = f.text_field :dn
          .small-3.columns
            = button_tag "Add", class:"postfix"
      - @group.uniquemember.each do |member|
        .row
          .small-9.columns
            = member
          .small-3.columns
            = form_for Ldap::GroupMember.new, url: admin_group_groups_members_path(@group.cn), method: :delete do |f|
              = f.hidden_field :dn, value: member
              = f.button "Remove", class:"button tiny alert", data: { confirm: "#{t('ldap.group.member.remove_are_you_sure')} #{member}?" }

app/views/admin/groups/edit.haml
.row
  .large-12.columns
    = render 'breadcrumbs'


= render 'form'

app/views/admin/groups/index.haml
.row
  .large-9.columns
    .row.collapse
      .small-10.columns
        = text_field_tag "search", "search"
      .small-2.columns
        = link_to "#", class: "button postfix" do
          = fa_icon 'search'
    .row
      .small-12.columns
        %dl.sub-nav
          %dt
            Filter:
          %dd.active
            = link_to "All", "#"
  .large-3.columns
    = link_to new_admin_group_path, class: "button postfix" do
      = fa_icon 'plus'
      Create

.row
  .large-12.columns
    %table.table-expand
      %thead
        %tr
          %th
            cn
          %th
            description
          %th
            objectclass
          %th
            gid
      %tbody
        - @groups.each do |group|
          %tr
            %td
              = link_to group.cn, edit_admin_group_path(group.cn)
            %td
              = group.description
            %td
              = group.objectclass
            %td
              = group.gidnumber

app/views/admin/groups/new.haml
- flash.each do |name, msg|
  .row
    .large-push-3.large-6.columns
      %div{class: flash_class(name) }
        = msg

= form_for @group, url:admin_groups_path, method: :post do |f|
  .large-5.columns
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          DN
      .small-9.columns
        = f.text_field :dn, disabled:true
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          CN
      .small-9.columns
        = f.text_field :cn
      = field_error_message(@group, :cn)
    .row.collapse.prefix-radius
      .small-3.columns
        %span.prefix
          Gid Number
      .small-9.columns
        = f.text_field :gidnumber
      = field_error_message(@group, :gidnumber)
    .row.collapse.prefix-radius
      %label
        %span.prefix
          Description
        = f.text_area :description
      = field_error_message(@group, :description)
    = f.button "Create"