config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  root 'people#index'

  resources :people, constraints: {id: /[A-Za-z0-9\._-]+/}, only: [:show, :photo] do
    get :photo
  end
  resource :sessions, only: [:new, :create, :destroy] do
  end
  resource :profile, only: [:edit, :update_passowrd] do
    patch :update_passowrd
    patch :update_photo
  end

  namespace :api do
    namespace :public do
      namespace :v1 do
        resources :people_photo, only: [:show], constraints: {id: /[A-Za-z0-9\._-]+/}
      end
    end
  end

  namespace :admin do
    constraints CanAccessResque do
      mount Resque::Server, at: 'resque'
    end

    get '', to: redirect('/admin/people'), as: :index
    resources :people, constraints: {id: /[A-Za-z0-9\._-]+/} do
      resource :people_photo, constraints: {person_id: /[A-Za-z0-9\._-]+/}, only: [:update] do
      end
    end

    resources :groups, constraints: {id: /[A-Za-z0-9\._-]+/} do
      resource :groups_members, constraints: {group_id: /[A-Za-z0-9\._-]+/}, only: [:create, :destroy] do
      end
    end
  end

end

app/views/layouts/admin.haml
- content_for :content do
  .row
    .large-11.push-1.columns
      = yield
    .large-1.pull-11.columns
      %ul.side-nav
        %li{ class: is_active?("admin/people")}
          = link_to admin_people_path do
            User
        %li{ class: is_active?("admin/group")}
          = link_to admin_groups_path do
            Group

  %footer.row
    .large-12.columns
      %hr
      .row
        .large-6.columns
          %p
            LdapControl
        .large-6.columns
          -#%ul.inline-list.right
          -#  %li
          -#    = link_to "#" do
          -#      Section 1
          -#  %li
          -#    = link_to "#" do
          -#      Section 2

= render :file => 'layouts/application'

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title
      = yield_or_default(:title)
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    .row
      .large-12.columns
        %nav.top-bar{"data-topbar" => ""}
          %ul.title-area
            %li.name
              %h1
                =link_to "LdapControl", root_path
            %li.toggle-topbar.menu-icon
              = link_to "#" do
                %span
                  menu
          %section.top-bar-section
            %ul.right
              %li.divider
              %li{ class: is_active?("^people")}
                = link_to "Home", root_path
              %li.divider
              %li{ class: is_active?("^admin")}
                = link_to "Admin", admin_index_path
              %li.divider
              %li{ class: is_active?("^settings")}
                = link_to "Settings", admin_index_path
              %li.divider
              %li.avatar{ class: is_active?("^profiles")}
                = link_to edit_profile_path do
                  = image_tag person_photo_path(current_user.uid, size: 'small'), class: "current-user_plugin-photo"
                  = current_user.cn
              %li.divider
              %li
                = link_to sessions_path, method: :delete do
                  Logout
    .content-margin
    = content_for?(:content) ? yield(:content) : yield

app/views/layouts/session.haml
!!! 5
%html
  %head
    %title
      = yield_or_default(:title)
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = content_for?(:content) ? yield(:content) : yield